### DISCUSSION TITLE
How with the 'backward-compatibility-check' command chech 2 files

### DISCUSSION THREAD

**Discussion by zanimonets** [specmatic/specmatic#1559] [Ask For Help] [answered]
The 'specmatic compare openapi1.yaml openapi2.yaml' works fine and marked as deprecated
But it's not clear how to do the same with 'backward-compatibility-check' 
Attempts
1) specmatic backward-compatibility-check --target-path openapi1.yaml openapi2.yaml -> Unmatched argument at index (probably because it only supports one argument)
2) With specmatic.yaml
```
sources:
  - provider: filesystem
    provides:
      - openapi1.yaml
```
and specmatic backward-compatibility-check --target-path openapi2.yaml -> 1. Running the check for openapi2.yaml:
read(...) must not be null
