### DISCUSSION TITLE
Reason: Conversion = 'P' error while running specmatic in azure devops

### DISCUSSION THREAD

**Discussion by akashchekka** [specmatic/specmatic#1883] [Ask For Help]
I am trying to run specmatic in pipeline and I have my spec file in a repository. I have added git url and branch details in specmatic.yaml file. Below are details:

## specmatic.yaml:
```yaml
version: 2
contracts:
  - git:
      url: https://dev.azure.com/<org>/test%20project/_git/<repo>
      branch: Specmatic-test
  - provides:
      - specmatic/usersapi/user-spec.yaml
```

## pipeline:
```yaml
- task: AzureCLI@2
  displayName: 'Execute Specmatic'
  inputs:
    azureSubscription: '$(SubscriptionServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |    
        git config --global url."https://$(System.AccessToken)@dev.azure.com/".insteadOf "https://dev.azure.com/"

        for i in {1..20}; do
          if curl -k --silent https://<IP>:$(PORT)/api/ping > /dev/null; then
            echo "API is ready!"
            break
          else
            echo "Waiting for API... ($i)"
            sleep 5
          fi
        done

        docker pull znsio/specmatic:latest

        docker run --rm --network=host \
          -v "$(Build.SourcesDirectory)/SRC/ContractTests/Specmatic:/usr/src/app" \
          -e BearerAuth=*** \
          znsio/specmatic test --testBaseURL=https://<IP>:$(PORT)
```
      
## Pipeline error:
```log
Contract repo does not exist.
Cloning https://dev.azure.com/<org>/test%20project/_git/<repo> into .specmatic/repos
Resetting /usr/src/app/.specmatic/repos/<repo>
Load Error has FAILED
Reason: Conversion = 'P'
```

Can I please get some help here?

UPDATED by @harikrishnan83: Improved formatting for readability
