### DISCUSSION TITLE
How to set BearerAuth token for test

### DISCUSSION THREAD

**Discussion by tkrisztian95** [specmatic/specmatic#913] [Ask For Help] [answered]
Im trying to pass a fixed token for testing in CI. According to docs https://specmatic.in/documentation/authentication.html#bearer-real it should be possible by setting the `BearerAuth` variable. 

In the API docs I have:

```
paths:
  /foo:
    post:
      security:
        - BearerAuth: []
...

components: 
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, for documentation purposes only
```

I've tried it multiple ways:
- In `specmatic.json` defined an environment `staging` and added in the `"environments": { "staging": { "variables": { "BearerAuth": " ..." }` .
- In test `setUp` added `System.setProperty("environment", "staging");`
- Set local `BearerAuth` ENV var for the current terminal.
- Set as java prop via `System.setProperty("BearerAuth", "..")`.

But, none of these worked. When I run Specmatic test (the `SpecmaticJUnitSupport` test class), it keeps sending a random generated text as Bearer in the request.

```
  Request to http://localhost:9100 at 2024-1-10 9:42:11.256
    POST /foo
    Authorization: Bearer JCAET
    Accept-Charset: UTF-8
    Accept: */*
```

Thanks!

---
**Update:** Im using some old version of the Specmatic junit support in my project `pom.xml`. So maybe that's causing this issue.
```
        <dependency>
            <groupId>in.specmatic</groupId>
            <artifactId>junit5-support</artifactId>
            <version>0.81.0</version>
            <scope>test</scope>
        </dependency>
```
