### ISSUE TITLE
API response not being validated with OpenAPI Response's example

### ISSUE THREAD

**Issue by hrishabh-kumar** [specmatic/specmatic#1048]
**Description**
API response not being validated with OpenAPI Response's example. Is this correct behaviour?

**Steps to reproduce**
1. I am referring to same example given in docs [page](https://specmatic.in/getting_started.html#petstore-api-specification). I am just trying to validate if the API is returning incorrect response, are we failing the test or not. 

So I have made a modification in given example under `responses` section in the local `service.yaml` file:

**Actual**:
```
      examples:
        SCOOBY_200_OK:
          value:
            id: 1
            name: Scooby
            type: Golden Retriever
            status: Adopted
```
**Modified**:
```
      examples:
        SCOOBY_200_OK:
          value:
            id: 1
            name: Charlie                      # Changed the name of the pet
            type: Golden Retriever
            status: Adopted
```

2. Run this command: 
`npx specmatic test service.yaml --testBaseURL=https://my-json-server.typicode.com/znsio/specmatic-documentation`

**Expected behavior**

As per the OpenAPI spec's example, we should expect the response with: `"name": "Charlie"`
```
{
  "id": 1,
  "name": "Charlie",
  "type": "Golden Retriever",
  "status": "Adopted"
}
```

But the response from curl is different `"name": "Scooby"`

Command: `curl https://my-json-server.typicode.com/znsio/specmatic-documentation/pets/1` is returning below json is response
```
{
  "id": 1,
  "name": "Scooby",
  "type": "Golden Retriever",
  "status": "Adopted"
}
```

So I was expecting that test will fail but it's getting successful. Is this correct behaviour? Are we not validating API response's each individual field with respect to example in `yaml` file (as test cases)?

<img width="684" alt="image" src="https://github.com/znsio/specmatic/assets/140509486/7abc13d2-86a9-45a0-be55-8ae453980aba">

**System Information:**
 - Browser & version: [chrome]
 - Specmatic version: [1.3.9]
 - JDK version: [21.0.2]
