### ISSUE TITLE
BearerAuth token not getting generated (1.3.11)

### ISSUE THREAD

**Issue by yogeshnikam671** [specmatic/specmatic#1072]
With this change, does it mean that I should be able to set:

`System.setProperty("BearerAuth", "abcdef");`

when my API Spec contains:

```
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

I'm not able to get this working. 

My understanding is that Specmatic should automatically create a dummy Authorization header on requests without setting any properties / environment variables, but it is not even doing that. I've also tried various ways of setting environment variables, but still doesn't result in any authorization headers getting included on the request. 

Any ideas? 

I am using 1.3.11 which includes the changes in this PR.

Thanks.

_Originally posted by @noelmccrory in https://github.com/znsio/specmatic/issues/1055#issuecomment-2064878462_
