### ISSUE TITLE
Specmatic Stub does not generate correct response for single JSON string

### ISSUE THREAD

**Issue by noelmccrory** [specmatic/specmatic#1087]
**Description**
I have a Spring Boot API which uses an enum as the ResponseEntity type:

`public ResponseEntity<DocumentStatus> getDocumentStatus(@PathVariable UUID id)`

When I call my API it produces the following response:

```
content-type: application/json
body: "COMPLETE"
```

(Note: the double quotes which make this valid json)

The OpenAPI Spec (which was autogenerated from `springdoc`) has:

```
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                enum:
                  - IN_PROGRESS
                  - COMPLETE
                  - FAILED
              examples:
                GET_DOCUMENT_STATUS:
                  value: COMPLETE
```

When I run the Specmatic Stub and call this endpoint, it returns the following:

```
    200 OK
    X-Specmatic-Result: success
    Content-Type: text/plain
    
    COMPLETE
```

Note: The double quotes are missing and the Content Type is wrong. This then results in an error on the consumer tests:

`Could not extract response: no suitable HttpMessageConverter found for response type [class com.xxxx.model.DocumentStatus] and content type [text/plain]`

Even if I update an API Spec to force the double quotes, it still results in `Content-Type: text/plain`:

```
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
                enum:
                  - '"IN_PROGRESS"'
                  - '"COMPLETE"'
                  - '"FAILED"'
              examples:
                GET_DOCUMENT_STATUS:
                  value: '"COMPLETE"'
```

**Steps to reproduce**
See above.

**Expected behavior**
Content-Type should be `application/json` and the string in the response body should be wrapped in double quotes.

**Screenshots**
N/A

**System Information:**
 - OS & version: MacOS 14.4.1
 - Specmatic version: 1.3.13
 - JDK version: 21

**Additional context**
It looks like a similar issue was present on the request generation - https://github.com/znsio/specmatic/issues/898

It seems similar to this issue - https://github.com/mock-server/mockserver/issues/1101

This is valid JSON according to https://jsonlint.com/
<img width="221" alt="image" src="https://github.com/znsio/specmatic/assets/11225700/40c5d221-76d7-4533-ad13-f41fef223934">
