### ISSUE TITLE
Specmatic shows that, contracts are not backward compatible for same OpenAPI files.

### ISSUE THREAD

**Issue by dilanka-cacib** [specmatic/specmatic#1371]
**Description**
When I use same OpenAPI file to compare for backward compatibility check. It gives result as '**The newer contract is not backward compatible**'

**Steps to reproduce**
1. Download this file: [openapi_specmatic_issue_demo.zip](https://github.com/user-attachments/files/17469916/openapi_specmatic_issue_demo.zip) and extract it and use latest [specmatic.jar](https://github.com/znsio/specmatic/releases/download/2.0.30/specmatic.jar)
2. Run this command (windows): java -jar specmatic.jar compare openapi_specmatic_issue_demo.yaml openapi_specmatic_issue_demo.yaml

**Expected behavior**
Since I am using the same OpenAPI file, it should give the result as 'The newer contract is backward compatible.'. But I receive the result as 'The newer contract is not backward compatible.'

**Screenshots**
![image](https://github.com/user-attachments/assets/c0f8b8fc-6f89-403f-b2de-c3e660c875b0)

**System Information:**
 - OS & version: [Windows 10 Enterprise]
 - Specmatic version: [[2.0.30](https://github.com/znsio/specmatic/releases/tag/2.0.30)]
 - JDK version: [java 17.0.7 2023-04-18 LTS]

**Comment by yogeshnikam671** [comment]
Hi @dilanka-cacib, thanks for reporting this issue. We will look into this and get back to you.

**Comment by yogeshnikam671** [comment]
Hi @dilanka-cacib,

It looks like the issue you're facing is due to conflicting constraints in the `iso2Code` schema:

```yaml
        - name: iso2Code
          in: path
          description: iso2Code
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 2
            pattern: .+
            type: string
```

In this case, `maxLength: 2` limits the `iso2Code` to 2 characters, while the `pattern` `.+` allows any length greater than 1. These conflicts are causing inconsistent behavior in Specmatic.

To resolve this, updating the schema to the following should fix the issue:

```yaml
        - name: iso2Code
          in: path
          description: iso2Code
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 2
            pattern: ^.{1,2}$
            type: string
```

This ensures the `pattern` and `maxLength` are aligned. We're also planning to address this nuance in Specmatic soon.

Let us know if you need further assistance, and feel free to reopen the issue if it's not resolved.

Best regards!
