### ISSUE TITLE
Support `baseURL` for Stub Server

### ISSUE THREAD

**Issue by harikrishnan83** [specmatic/specmatic#1431]
**Is your feature request related to a problem? Please describe.**
Many a times, the API path needs to be prefixed with additional path segments. Example: `/products` needs to be prefixed with `/api/store/`.

**Describe the solution you'd like**
Support either both or at least one capability.
* Support `baseURL` similar to `testBaseURL` for stub server
* Pick it up from `servers` section

**Additional context**
Creating this on behalf of @twinkle12b as a follow-up to issue #1425

**Comment by twinkle12b** [comment]
Hello thanks for opening this request, can you help me resolve the issue of how can I also do this for my stub server as it is also not able to detect the server url path, like i can set system property for testbaseurl base path for contract as test. How can i do this for stub server basepath

**Comment by twinkle12b** [comment]
Hey @harikrishnan83  @samyakOO7  any updates on the question???

**Comment by harikrishnan83** [comment]
hello @twinkle12b, thanks for following up on this.

We are already working on option 1 "_Support baseURL similar to testBaseURL for stub server_" mentioned above. And should be available shortly.

Meanwhile on option 2 "_Pick it up from servers section_", the servers section in OpenAPI 3.0.x, as you may be aware, can have multiple servers.

```yaml
servers:
  - url: https://api.production.example.com/v1
    description: Production server
  - url: https://api.staging.example.com/v1
    description: Staging server
  - url: http://localhost:8080/v1
    description: Local development server
```

So to pick one of them we plan to use `description` field as the identifier for the URL. So the syntax may look something like `specmatic test --server "Local development server"` or `specmatic virtualize/stub --server "Local development server"`. Any thoughts on this?

Thanks.

cc @samyakOO7
