### ISSUE TITLE
stub not matching expectations after 2.7.1

### ISSUE THREAD

**Issue by juanjobt** [specmatic/specmatic#1669]
**Description**
I was using some expectations on an endpoint where the response varied based on a query parameter. When using version 2.7.2, I encountered issues resolving the expectations.

**Steps to reproduce**
I start a Docker Compose setup with the following service:
```
api-stub:
    image: znsio/specmatic:2.7.1
    ports:
      - "8080:8080"
    volumes:
      - ./tests/Acceptance/resources/apiStub/service.yaml:/specs/service.yaml
      - ./tests/Acceptance/resources/apiStub/expectations:/specs/service_data
    command: stub /specs/service.yaml --strict --port 8080
```

This setup includes the following service.yaml:
```
openapi: 3.0.1
info:
  title: Contract for the service
  version: '1'
paths:
  /v0/pipes/changes.json:
    get:
      parameters:
        - $ref: '#/components/parameters/reference'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
components:
  parameters:
    reference:
      in: query
      name: reference
      schema:
        type: string
```

I also have two expectations

```
{
    "http-request": {
        "method": "GET",
        "path": "/v0/pipes/changes.json",
        "query": {
            "reference": "22222"
        }
    },
    "http-response": {
        "status": 200,
        "body": {}
    }
}
```
```
{
    "http-request": {
        "method": "GET",
        "path": "/v0/pipes/changes.json",
        "query": {
            "reference": "11111"
        }
    },
    "http-response": {
        "status": 200,
        "body": {}
    }
}
```

In version 2.7.1, everything works correctly, and Specmatic stub returns the expected response based on the query parameter. However, after updating to 2.7.2, it stops working and always returns an error like >> REQUEST.QUERY-PARAMS.reference

   Stub expected "22222" but request contained "11111"

Is there a specific reason for this behavior? Is this an intentional change or a feature to be aware of?

Thank you for your work. Best regards.
