### ISSUE TITLE
Examples values surrounded by rounded brackets fails.

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#1728]
**Description**
When running Specmatic tests with examples that contain rounded brackets, such as "(stringval)," an error occurs:
```
 >> REQUEST.BODY
           
                      Type (stringval) does not exist
           
                   Type (stringval) does not exist
```

**Steps to reproduce**
1. Add example value similar to this:
```
examples:
      success:
          value: 
          message2: "(stringval)"
```
2. Run Specmatic tests.

**Expected behavior**
Testcase should take this as string value and work.

**System Information:**
 - Specmatic version:  v2.7.5(Python wrapper).
