### ISSUE TITLE
Test data generation for complicated regex in patterns

### ISSUE THREAD

**Issue by back2debug** [specmatic/specmatic#1750]
**Is your feature request related to a problem? Please describe.**
There are a lot of warnings when I run the tests for complicated regex where we have a regex pattern for an address.  Our spec has no examples but examples generated and modified. The data that winds up getting generated is junk.  The rest of the regex patterns in the spec are respected but much simpler.

```
WARNING: Please check the regex ^[\p{L}\p{M}0-9\-\.\'\ ]*$. We generated a random string p.}} and the regex does not match the string. 
```

**Describe the solution you'd like**
Try to leverage the examples files if it is struggling to generate data as a fallback maybe if the generation fails.
Instead of warning maybe fail so tests are not run with bad data
Improvements to random string to handle complex regex

**Describe alternatives you've considered**
We really don't want to have to downgrade or make major edits to our OpenApi specs to use the tool.

**Additional Notes**
OpenApi Spec 3.1 downgraded to 3.0.3
Specmatic 2.7.8 via npm
```
components:
  schemas:
    Address:
      type: object
      required:
        - address_line_1
      properties:
        address_line_1:
          type: string
          description: The first line of the owner's address.
          pattern: '^[\p{L}\p{M}0-9\-\.\''\ ]+$'
```
