### ISSUE TITLE
Externalizing payload does not work

### ISSUE THREAD

**Issue by GagandeepSharma060** [specmatic/specmatic#1884]
So i have a spec file in which initially i passed the payload as follows
```
            examples:
              test_put_case_1:
                value:
                  name: user1
                  email: user1@test.com
```

The above is working fine.

But now when I try to externalize this ayload i am getting error.
I am trying
```
            examples:
              test_put_case_1:
                  $ref: "../test-controller/payload/payload.yaml#/payload1"
```

with payload.yaml file having content: 
```
payload1:
  value:
    name: user1
    email: user1@test.com
```

SO I am getting error:

```
          >> REQUEST.BODY
  
             Could not parse json object, got error: Unexpected JSON token at offset 19: Expected colon ':', but had ',' instead at path: $
             JSON input: {name=user1,user1@test.com}
```

Can someone please check
