### ISSUE TITLE
Unable to stub multiple HTTP methods on the same path

### ISSUE THREAD

**Issue by tpwst555** [specmatic/specmatic#543]
We have PATCH and GET methods on the same path.  When I submit the PATCH, the server responds that it is expecting a GET.

To reproduce:

1) Create a spec with GET and PATCH on the same path:
```
paths:
  /myResources/{myResourceId}:
    get:
      operationId: getMyResource
 ...
   patch:
      operationId: patchMyResource
      parameters:
```

2) Submit a PATCH request.  Stub server responds:
```
  Response at 2022-11-7 4:8:37.807
    400 Bad Request
    Content-Type: text/plain
    X-Specmatic-Result: failure
    
    In scenario "GET /myResources/(myResourceId:number). Response: OK"
    API: GET /myResources/(myResourceId:number) -> 200
    
      >> REQUEST.METHOD
      
         Expected GET, actual was PATCH
```
Expected behavior: 
Multiple HTTP Methods can be stubbed on the same path.

Specmatic v0.55.0
