### ISSUE TITLE
load error java.lang.Boolean cannot be cast to io.swagger.v3.oas.models.media.Schema.

### ISSUE THREAD

**Issue by MishaTyupa** [specmatic/specmatic#646]
**Description**
One example of when it is not working and we are getting a casting error when we try to run specmatic test with swagger YAML file is when we have the following YAML(that's a part of swagger YAML file)
```
    SomeService:
      type: object
      properties:
        name:
          type: string
          nullable: true
        host:
          type: string
          nullable: true
        hostName:
          type: string
          nullable: true
      **additionalProperties: false**
```

It cannot be parsed and I'm getting a java error: `load error java.lang.Boolean cannot be cast to io.swagger.v3.oas.models.media.Schema.` If I remove `additionalProperties: false`, then it works. So definitely something that can be improved to cast such YAML also. There are more examples when it failed to cast `additionalProperties: {}` etc.

**Steps to reproduce**
1. run specmatic test using swagger open API (3.0.1 version)

**Expected result**
Tests are executed
