### ISSUE TITLE
Specmatic Docker image for backward compatibility checks in CI example

### ISSUE THREAD

**Issue by tkrisztian95** [specmatic/specmatic#941]
**Is your feature request related to a problem? Please describe.**
Can I use the Specmatic Docker image for backward compatibility checking from a GitLab merge request pipeline?

**Describe the solution you'd like**
Please add an example to the docs for a GitLab CI job using the Specmatic Docker image.

**Additional context**
There is only the jar command usage example in [the docs here](https://specmatic.in/documentation/backward_compatibility.html#validating-changes-in-ci).

**Comment by harikrishnan83** [comment]
@tkrisztian95 Thanks for bring this up. Will look into it.

**Comment by tkrisztian95** [comment]
I have a minimal working example for  `merge_request` pipelines on GitLab. 

This is how I made it work: 
```yml
check:backward-compatiblity:merge:
  stage: check
  allow_failure: true
  image:
    name: znsio/specmatic:1.2.12
    entrypoint: [""]
  script:
    - echo "Commit - $CI_COMMIT_SHA"
    - echo "Target branch - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - git fetch --depth 1 origin $CI_MERGE_REQUEST_DIFF_BASE_SHA
    - files=$(git diff --no-commit-id --name-only -r $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA)
    - echo "Changed files:"
    - echo $files
    - |
      for i in $files;
      do
        if echo "$i" | grep -Eq '[.](yaml)$'; then
          echo "Running backward compatibility check on: $i"
          echo "$i" | tr -s ' ' '\n' | xargs -I % java -jar /usr/src/app/specmatic.jar compatible git commits % "$CI_COMMIT_SHA" "$CI_MERGE_REQUEST_DIFF_BASE_SHA"
        else
          echo "Skip backward compatibility check on: $i"
        fi
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
```

**Comment by harikrishnan83** [comment]
@tkrisztian95 that is great. Thanks for sharing this. We will link your above comment in our documentation. I am sure other users will also benefit from your solution.

Our compatibility stage on Gitlab looks quite similar too.

```yaml
compatibility:
  stage: compatibility
  image:
    name: znsio/specmatic:latest
    entrypoint: [""]
  before_script:
    - git fetch
    - git checkout main
    - git checkout "$CI_COMMIT_REF_NAME"
    - git status
  script:
    - find . -type f -name '*.yaml' -not -name '.*' | xargs -I % sh -c 'echo "File %"; java -jar /usr/src/app/specmatic.jar compatible git commits % HEAD main'
  allow_failure: true
  tags:
    - docker
```

Also wanted to update you that the [backward compatibility testing documentation](https://specmatic.in/documentation/backward_compatibility.html) now include docker commands alongside Java and npm.

Can we consider this issue closed?
